name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: ['**']
defaults:
    run:
        shell: bash

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run test
